//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManager.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarManager.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 返回集合页 的本地化字符串。
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车邮件 的本地化字符串。
        /// </summary>
        public static string CarViewModelEmailDisplayName {
            get {
                return ResourceManager.GetString("CarViewModelEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车名字 的本地化字符串。
        /// </summary>
        public static string CarViewModelNameDisplayName {
            get {
                return ResourceManager.GetString("CarViewModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车价格 的本地化字符串。
        /// </summary>
        public static string CarViewModelPriceDisplayName {
            get {
                return ResourceManager.GetString("CarViewModelPriceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string createButton {
            get {
                return ResourceManager.GetString("createButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName} 地址格式错误 的本地化字符串。
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName} 不能小于 {MinLength} 并且不能大于 {MaxLength} 的本地化字符串。
        /// </summary>
        public static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName} 不能为空 的本地化字符串。
        /// </summary>
        public static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
    }
}
